[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "*.md,*.txt,netlify/functions/**"
  SECRETS_SCAN_OMIT_KEYS = "APPLE_PASS_TYPE_ID,APPLE_ORG_NAME"

